on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: t2y/gh-actions-sample/@v4
        with:
          who-to-greet: 'Mona the Octocat'
          cli: ./mvnw --no-transfer-progress test
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: echo result ${{ steps.foo.outputs.cli-result }}
        shell: bash
